name: Init New Repo with Template

on:
  workflow_dispatch:
    inputs:
      org_name:
        description: "Name of the GitHub organization"
        required: true
        default: "ondc-official"
      repo_name:
        description: "Name of the new GitHub repo"
        required: true
      brief_description:
        description: "Short description of the repository"
        required: true
      category:
        description: "Select category"
        type: choice
        options:
          - specifications
          - reference-apps
          - automation-testing
          - mock-sandbox
          - adaptors
          - sdks
          - infrastructure
          - documentation
          - logs
      subcategory:
        description: "Select subcategory"
        type: choice
        options:
          - buyer-apps
          - seller-apps
          - logistics-apps
          - ecommerce
          - core-framework
          - services
          - mock-servers
      domain:
        description: "Select domain"
        type: choice
        options:
          - retail
          - logistics
          - agriculture
          - healthcare
          - financial
          - mobility
          - education
      type:
        description: "Select type"
        type: choice
        options:
          - frontend
          - backend
          - mobile
          - api
          - library
          - tool
          - documentation
      status:
        description: "Select status"
        type: choice
        options:
          - production
          - beta
          - alpha
          - experimental
          - deprecated
          - archived

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Check if organization exists and create repo
        run: |
          ORG="${{ github.event.inputs.org_name }}"
          REPO="${{ github.event.inputs.repo_name }}"

          echo "Checking org..."
          ORG_CHECK=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/orgs/$ORG)

          if [ "$ORG_CHECK" -ne 200 ]; then
            echo " Org '$ORG' not found or no access."
            exit 1
          fi

          echo " Org exists."

          echo "Checking repo..."
          REPO_CHECK=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$ORG/$REPO)

          if [ "$REPO_CHECK" -eq 200 ]; then
            echo " Repo '$REPO' already exists."
            exit 1
          fi

          DESC="${REPO}: [${{ github.event.inputs.category }}/${{ github.event.inputs.subcategory }}] ${{ github.event.inputs.brief_description }} | status: ${{ github.event.inputs.status }} | domain: ${{ github.event.inputs.domain }}"

          CREATE_RESP=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/orgs/$ORG/repos \
            -d "{\"name\":\"$REPO\",\"private\":false,\"description\":\"$DESC\"}")

          if [ "$CREATE_RESP" -eq 201 ]; then
            echo " Repo created: $ORG/$REPO"
          else
            echo " Failed with status $CREATE_RESP"
            exit 1
          fi

      - name: Add Topics to Repository
        run: |
          ORG="${{ github.event.inputs.org_name }}"
          REPO="${{ github.event.inputs.repo_name }}"

          TOPICS="[\"category-${{ github.event.inputs.category }}\",\"subcategory-${{ github.event.inputs.subcategory }}\",\"type-${{ github.event.inputs.type }}\",\"status-${{ github.event.inputs.status }}\",\"domain-${{ github.event.inputs.domain }}\"]"

          curl -X PUT \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$ORG/$REPO/topics \
            -d "{\"names\": $TOPICS}"

          echo " Topics added: $TOPICS"

      - name: Install Yeoman
        run: npm install -g yo

      - name: Clone Template Repo
        run: |
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/nmonga26/node-template.git template-repo

      - name: Prepare Yeoman Generator
        run: |
          mkdir -p generator-ondc-nodets/generators/app/templates
          cp -r template-repo/* generator-ondc-nodets/generators/app/templates/
          cp -r template-repo/.[!.]* generator-ondc-nodets/generators/app/templates/ || true

          # package.json for generator
          cat > generator-ondc-nodets/package.json <<'EOF'
          {
            "name": "generator-ondc-nodets",
            "version": "1.0.0",
            "description": "Yeoman generator wrapping ONDC Node TS template",
            "main": "generators/app/index.js",
            "dependencies": {
              "yeoman-generator": "^5.9.0"
            }
          }
          EOF

          # index.js for generator
          mkdir -p generator-ondc-nodets/generators/app
          cat > generator-ondc-nodets/generators/app/index.js <<'EOF'
          const Generator = require('yeoman-generator');

          module.exports = class extends Generator {
            writing() {
              this.fs.copyTpl(
                this.templatePath('**/*'),
                this.destinationPath('.'),
                {},
                {},
                { globOptions: { dot: true } }
              );
            }
          }
          EOF

          cd generator-ondc-nodets
          npm install
          npm link

      - name: Generate Project with Yeoman
        run: |
          mkdir -p ${{ github.event.inputs.repo_name }}
          cd ${{ github.event.inputs.repo_name }}
          yo ondc-nodets --skip-install --force --no-insight

      - name: Update Project Files with Repo Name
        run: |
          cd ${{ github.event.inputs.repo_name }}
          REPO_NAME="${{ github.event.inputs.repo_name }}"

          sed -i "s/test55-node-backend/$REPO_NAME/g" package.json || true
          sed -i "s/test55-node-backend/$REPO_NAME/g" package-lock.json || true
          sed -i "s/test55-node-backend/$REPO_NAME/g" README.md || true
          sed -i "s/test55-node-backend/$REPO_NAME/g" docker-compose.yml || true
          sed -i "s/test55-node-backend/$REPO_NAME/g" docker-compose.production.yml || true

      - name: Push to New Repo
        run: |
          cd ${{ github.event.inputs.repo_name }}
          rm -rf .git  #  remove template's git history
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git branch -M main
          git remote add origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.event.inputs.org_name }}/${{ github.event.inputs.repo_name }}.git
          git add .
          git commit -m "[skip ci]"
          git push origin main
